# Generated by Django 4.2.7 on 2023-11-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('channel_name', models.CharField(max_length=100)),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('comments', models.JSONField(default=list)),
                ('video_category', models.CharField(max_length=100)),
            ],
        ),
    ]
