# Generated by Django 4.2.7 on 2023-11-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='comments',
            field=models.JSONField(default=list, null=True),
        ),
    ]
