# Generated by Django 4.2.7 on 2023-11-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_video_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
