# Generated by Django 4.2.7 on 2023-11-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_video_id_alter_video_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='video',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
