# Generated by Django 4.2.7 on 2023-11-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_video_image_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='comments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
