# Generated by Django 4.2.7 on 2023-11-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_video_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uploaded_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
