# Generated by Django 4.2.7 on 2023-11-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_video_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
